### ISSUE TITLE
ckan 2.3 and csw harvest problem

### ISSUE THREAD

**Issue by lcipriani** [ckan/ckanext-spatial#143] opened 2016-01-22 13:03 UTC
With csw job i have this error, is a ckan version problem ? 

2016-01-22 11:22:58,230 INFO  [ckanext.harvest.model] Error contacting the CSW server: __init__() takes exactly 1 argument (2 given)
2016-01-22 11:22:58,236 ERROR [ckanext.harvest.queue] Gather stage failed

Thanks!

**Comment by tomkralidis** [comment] 2016-01-23 20:33
I'm guessing this is somehow a result of fc4c37c4c31b005853c59e2880a1a82ed9035435. I'll try to look deeper in the coming days

**Comment by lcipriani** [comment] 2016-01-25 08:46
Hi thanks, tomkralidis .
I have looked the csw_client.py file, but there is the line:
+ super(CswService, self).__init__()

**Comment by amercader** [comment] 2016-01-25 15:25
Yes, this was caused by changing the `__init__` mehod params. 

@tomkralidis the parent class `OwsService` requires an `endpoint` param so we need something like:

```diff
diff --git a/ckanext/spatial/lib/csw_client.py b/ckanext/spatial/lib/csw_client.py
index a592464..207a0d4 100644
--- a/ckanext/spatial/lib/csw_client.py
+++ b/ckanext/spatial/lib/csw_client.py
@@ -67,8 +67,8 @@ class CswService(OwsService):
     """
     from owslib.csw import CatalogueServiceWeb as _Implementation
 
-    def __init__(self):
-        super(CswService, self).__init__()
+    def __init__(self, endpoint=None):
+        super(CswService, self).__init__(endpoint)
         self.sortby = SortBy([SortProperty('dc:identifier')])
 
     def getrecords(self, qtype=None, keywords=[],
```

**Comment by tomkralidis** [comment] 2016-01-25 15:36
Thanks @amercader.  PR issued in #144 144

**Comment by lcipriani** [comment] 2016-01-26 11:32
Thanks!  @amercader

**Comment by amercader** [comment] 2016-01-26 17:03
Merged, thanks both

**Closed** 2016-01-26 17:03 UTC

**Comment by etj** [comment] 2016-06-21 08:48
It seems that this fix has not been ported to the ``stable`` branch::
https://github.com/ckan/ckanext-spatial/blob/stable/ckanext/spatial/lib/csw_client.py#L70-L71
